# Generated by Django 3.0.7 on 2022-06-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_alter_answer_id_alter_answerhelpful_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
