# Generated by Django 4.0 on 2022-06-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_auto_20220619_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='slug',
            field=models.SlugField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
