# Generated by Django 3.1.4 on 2021-02-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(default='sug', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
