# Generated by Django 4.1.6 on 2023-05-05 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_alter_answer_slug_alter_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='_description',
        ),
    ]
