# Generated by Django 5.0.4 on 2024-05-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0005_rename_description_category__description'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_rich_text',
            field=models.BooleanField(default=False),
        ),
    ]
