# Generated by Django 3.1.4 on 2021-02-19 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0007_auto_20210218_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqcomment',
            name='question',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='faq.question'),
            preserve_default=False,
        ),
    ]
