# Generated by Django 3.1.4 on 2021-02-19 00:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0008_faqcomment_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqcomment',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
