# Generated by Django 3.1.4 on 2021-02-19 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0010_auto_20210218_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqcomment',
            options={'ordering': ['question', '-post_time']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='answer',
            order_with_respect_to='question',
        ),
    ]
