# Generated by Django 3.1.4 on 2021-02-19 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faq', '0011_auto_20210218_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpful',
            name='answer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='faq.answer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helpful',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helpful',
            name='vote',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
