# Generated by Django 3.1.4 on 2021-02-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0012_auto_20210218_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helpful',
            options={'ordering': ['answer', 'vote']},
        ),
        migrations.AddField(
            model_name='answer',
            name='slug',
            field=models.SlugField(default='the'),
            preserve_default=False,
        ),
    ]
