# Generated by Django 3.1.4 on 2021-02-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0013_auto_20210219_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='slug',
            field=models.SlugField(max_length=10, unique=True),
        ),
    ]
