# Generated by Django 3.1.4 on 2021-02-21 02:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faq', '0014_auto_20210219_1609'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Helpful',
            new_name='AnswerHelpful',
        ),
        migrations.AlterField(
            model_name='answer',
            name='slug',
            field=models.SlugField(max_length=10),
        ),
    ]
