# Generated by Django 3.1.4 on 2021-02-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0015_auto_20210220_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='helpful',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='not_helpful',
            field=models.IntegerField(default=0),
        ),
    ]
