# Generated by Django 3.1.4 on 2021-02-21 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faq', '0016_auto_20210220_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='helpful',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='not_helpful',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='QuestionHelpful',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.BooleanField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faq.answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['answer', 'vote'],
            },
        ),
    ]
