# Generated by Django 3.1.4 on 2021-02-21 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0017_auto_20210220_2143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionhelpful',
            options={'ordering': ['question', 'vote']},
        ),
        migrations.RemoveField(
            model_name='questionhelpful',
            name='answer',
        ),
        migrations.AddField(
            model_name='questionhelpful',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='faq.question'),
            preserve_default=False,
        ),
    ]
