name: Test django-easy-faq

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build/Test (Python ${{ matrix.python-version }}, Django ${{ matrix.django-version }})
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10", "3.12", "3.14"]
        django-version: ["6.0", "5.2", "5.1"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }} & Django ${{ matrix.django-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set env (Python ${{ matrix.python-version }}, Django ${{ matrix.django-version }})
        run: echo "RELEASE_VERSION=0.0.1" >> $GITHUB_ENV
      - name: Install Dependencies (Python ${{ matrix.python-version }}, Django ${{ matrix.django-version }})
        run: |
          pip install django-tinymce
          pip install "Django==${{ matrix.django-version }}"
          pip install -e .
      - name: Run Tests (Python ${{ matrix.python-version }}, Django ${{ matrix.django-version }})
        run: |
          cd example
          python manage.py test faq
